name: localize_and_translate
description: Flutter localization in easy steps, simple ways to localize and translate your app
version: 4.0.1
homepage: https://github.com/msayed-net/localize_and_translate

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.17
  devicelocale: ^0.5.5
